[package]
name = "rust_calculator"
version = "0.1.0"
edition = "2021"
authors = ["jotavetech"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.18.1"
evalexpr = "11.3.0"

